name: GitHub Actions Demo
on: [push]
jobs:
  Build-Focal-Travis:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y
             g++ qt5-default
             python3-dev ninja-build zlib1g-dev libssl-dev libffi-dev libgl-dev
             libboost-all-dev libdouble-conversion-dev libgsl-dev libcairo2-dev
             libpoppler-qt5-dev libkf5itemmodels-dev imagemagick
      - name: Checkout lib2geom
        run: |
          git clone https://gitlab.com/inkscape/lib2geom.git
          cd lib2geom
          git checkout 37876ed4
          cd ..
      - name: configure lib2geom
        run: cmake -S lib2geom
                   -B build-lib2geom
                   -GNinja
                   -D2GEOM_TESTING=OFF
                   -DCMAKE_INSTALL_PREFIX=install
      - name: build lib2geom
        run: cmake --build build-lib2geom --target install
      - name: configure omm
        run: cmake -S ${{ github.workspace }}
                   -B build
                   -GNinja
                   -DCMAKE_BUILD_TYPE=Release
                   -DQT_QM_PATH=/usr/share/qt5/translations/
                   -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: build omm
        run: cmake --build build --target package
