name: Build on Ubuntu Focal
on: [push]
jobs:
  Build-lib2geom-Focal:
    runs-on: ubuntu-20.04
    steps:
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y
           build-essential
           cmake
           g++
           libboost-all-dev
           libdouble-conversion-dev
           ninja-build
      - run: git clone https://gitlab.com/inkscape/lib2geom.git
      - run: cd lib2geom; git checkout 37876ed4; cd ..
      - run: cmake -S lib2geom
                   -B build-lib2geom
                   -GNinja
                   -D2GEOM_TESTING=OFF
                   -DCMAKE_BUILD_TYPE=Release
                   -DCMAKE_INSTALL_PREFIX=lib2geom-install
      - run: sudo cmake --build build-lib2geom
                        --target install
                        --config Release
                        -j4
      - uses: actions/upload-artifact@v2
        with:
          name: lib2geom-focal
          path: lib2geom-install
  Build-libommpfritt-Focal-gcc:
    runs-on: ubuntu-20.04
    needs: Build-lib2geom-Focal
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-focal
      - uses: actions/download-artifact@v2
        with:
          name: lib2geom-focal
          path: lib2geom-install
      - run: cmake -S ${{ github.workspace }}
                   -B build
                   -GNinja
                   -DCMAKE_BUILD_TYPE=Release
                   -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
                   -DCMAKE_PREFIX_PATH=lib2geom-install
                   -DBUILD_TESTING=ON
                   -DGENERATE_ICONS=ON
      - run: cmake --build build
                   --target libommpfritt
                   --config Release
                   -j4
      - uses: actions/upload-artifact@v2
        with:
          name: libommpfritt-focal-gcc
          path: build
  Configure-libommpfritt-Focal-clang:
    runs-on: ubuntu-20.04
    needs: Build-lib2geom-Focal
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-focal
      - uses: actions/download-artifact@v2
        with:
          name: lib2geom-focal
          path: lib2geom-install
      - run: cmake -S ${{ github.workspace }}
                   -B build
                   -GNinja
                   -DCMAKE_BUILD_TYPE=Release
                   -DQT_QM_PATH=/usr/share/qt5/translations/
                   -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
                   -DCMAKE_PREFIX_PATH=lib2geom-install
                   -DCMAKE_CXX_COMPILER=clang
                   -DCMAKE_C_COMPILER=clang
      - uses: actions/upload-artifact@v2
        with:
          name: libommpfritt-focal-clang
          path: build
  Build-libommpfritt-Focal-clang:
    runs-on: ubuntu-20.04
    needs: Configure-libommpfritt-Focal-clang
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-focal
      - uses: actions/download-artifact@v2
        with:
          name: lib2geom-focal
          path: lib2geom-install
      - uses: actions/download-artifact@v2
        with:
          name: libommpfritt-focal-clang
          path: build
      - run: cmake --build build
                   --target libommpfritt
                   --config Release
                   -j4
  Build-ommpfritt-Focal-gcc:
    runs-on: ubuntu-20.04
    needs: Build-libommpfritt-Focal-gcc
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-focal
      - uses: actions/download-artifact@v2
        with:
          name: lib2geom-focal
          path: lib2geom-install
      - uses: actions/download-artifact@v2
        with:
          name: libommpfritt-focal-gcc
          path: build
      - run: cmake --build build
                   --target ommpfritt
                   --config Release
                   -j4
                   -- -d explain
      - uses: actions/upload-artifact@v2
        with:
          name: ommpfritt-focal-gcc
          path: build
  Clazy-Check:
    runs-on: ubuntu-20.04
    needs: Configure-libommpfritt-Focal-clang
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-focal
      - run: sudo apt-get update && sudo apt-get install clazy
      - uses: actions/download-artifact@v2
        with:
          name: libommpfritt-focal-clang
          path: build
      - uses: actions/download-artifact@v2
        with:
          name: libommpfritt-focal-clang
          path: build
      - run: |
          files="$(build-scripts/files.py --mode changed)"
          if [ -z "$files" ]; then
            echo "Skip clazy: No relevant files have changed."
          else
            clazy --standalone -p build --ignore-included-files $files
          fi
  Clang-Tidy-Check:
    runs-on: ubuntu-20.04
    needs: Configure-libommpfritt-Focal-clang
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-focal
      - run: sudo apt-get update && sudo apt-get install clazy
      - uses: actions/download-artifact@v2
        with:
          name: libommpfritt-focal-clang
          path: build
      - uses: actions/download-artifact@v2
        with:
          name: libommpfritt-focal-clang
          path: path
      - run: |
          files="$(build-scripts/files.py --mode changed)"
          if [ -z "$files" ]; then
            echo "Skip clang-tidy: No relevant files have changed."
          else
            clang-tidy -p build $(build-scripts/files.py --mode changed) $files
          fi
  Unit-Test-libommpfritt:
    runs-on: ubuntu-20.04
    needs: Build-libommpfritt-Focal-gcc
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-focal
      - uses: actions/download-artifact@v2
        with:
          name: libommpfritt-focal-gcc
          path: build
      - uses: actions/download-artifact@v2
        with:
          name: lib2geom-focal
          path: lib2geom-install
      - run: cmake --build build
                   --config Release
                   -j4
      - run: ctest --test-dir build
